version: "3"
services:
  authoragent:
      container_name: authoragent
      restart: always
      build: .
      ports:
      - "3000:3000"
      links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.4.6
    volumes:
    - ./data:/data/db
    ports:
    - '27017:27017'
  
 