version: "3"
services:
  registeragent:
      container_name: registeragent
      restart: always
      build: .
      ports:
      - "3001:3001"
      networks:
      - fabric_test
      volumes:
      - ./testlogs:/app/testlogs
networks:
  fabric_test:
    external: true
 