name: Build & publish agent images
on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]
    
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Implementation/AuthorAgent/Dockerfile
            image: authoragent
         # - dockerfile: ./src/Dockerfile-dril4net-distribution
          #  image: ghcr.io/username/image2
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: distributediot
          password: ${{ secrets.DISTRIBUTEDBCHFWARCHIOT_SECRET }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }
      - name: Build and push Docker Agent image
        env:
          CI: false
        uses: docker/build-push-action@v3
        with:
          context: ./Implementation/AuthorAgent
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
